### PR TITLE
Support for cryodrgn 0.3.3b

### PR DESCRIPTION
**Pull request by delarosatrevin**

### CODE REVIEW

**Comment by azazellochg** [comment]
I have added 0.33b support in devel branch already. Also, please make PRs to devel, not master since this is not a hotfix

**Comment by delarosatrevin** [comment]
I merged devel to this branch, so all your changes there are here. Moreover, "release branches" can also be merged to master ;)

**Comment by azazellochg** [comment]
I dont use "release branches", since the are tags when master is released. I'll let this one through, but it's then your responsibility to merge any changes to devel as master should not ever be ahead of devel

**Comment by delarosatrevin** [comment]
Ok, I canged the PR to devel...now we need to do two PR, this one and another one to master. I'm thinking that we might easily get rid of devel branch in plugins with no so much development going on.

**Comment by delarosatrevin** [comment]
Well, the other possibility is to do all changes in devel and then create always a release PR with tags and changes.

**Pull request closed without merging**
