### PR TITLE
major refactoring

### LINKED ISSUE #41: add v3.0 support
The downsampling/preprocessing step might need to be removed as 3.0 does not work on preprocessed data

### PR DESCRIPTION
**Pull request by azazellochg**
This closes #41 

3.12:
    - v3.1.0 added, old versions removed
    - refactor preprocess protocol to do only downsampling and/or chunking
    - refactor train_vae protocol, remove analysis step and add ctf/poses parse step, add continue option
    - refactor abinitio protocol, add output volume for homogeneous reconstruction
    - new analysis protocol with a viewer

New tests are passing wth 2.3.0 and 3.1.0. The only problem is ab init homo with 3.1.0 which fails due to a cryodrgn bug

### CODE REVIEW

**Comment by azazellochg** [comment]
@DavidHerreros please have a look as this might affect flexutils plugin. The most important change is the removal of "CryoDrgnParticles" which are replaced by a normal Scipion particle set.

**Comment by DavidHerreros** [comment]
Hi @azazellochg,

Thanks for the update of the CryoDRGN plugin! :)

I have tried to install the new version, run the tests, and encountered some errors on my laptop. I'm listing them here in case they may occur on other machines as well:

- When installing CryoDRGN binaries, I encountered an error while calling `pip install` from the downloaded repository. It seems the folder Scipion is in at that moment is `software/em`, when it should be `software/em/cryodrgn-3.1.0`. Calling `cd cryodrgn-{version} &&` before the pip install command seems to solve the issue.

- According to the conda-forge CudaToolkit channel, the latest uploaded version of the toolkit is `11.8.0`. In my case, the plugin was trying to install version `12.1.*` from that channel, leading to an error. It appears Nvidia has its own channel with a package called cuda-toolkit that offers a more updated version, although I have not tested if it works well.

- I have found that for GPUs like RTX 4000, there is a bug related to the CuFFT libraries that come with the CudaToolkit from conda-forge. To solve it, it is necessary to reinstall `libcufft` from the Nvidia conda channel in the environment. Otherwise, the tests might fail (I have already tested this on my machine).

**Comment by azazellochg** [comment]
Hi @DavidHerreros, thank you for a very quick response. The answers are below:

- cd into the folder is already done, not sure how you get an error:
```
cd /public/EM/Scipion/scipion-dev/software/em
mkdir /public/EM/Scipion/scipion-dev/software/em/cryodrgn-3.1.0
cd /public/EM/Scipion/scipion-dev/software/em/cryodrgn-3.1.0
cd .. && git clone -b v3.1.0-beta https://github.com/zhonge/cryodrgn.git cryodrgn-3.1.0 && cd cryodrgn-3.1.0; source /public/EM/Scipion/conda.rc&& conda create -y -n cryodrgn-3.1.0 python=3.10 && conda activate cryodrgn-3.1.0 && conda install -y cudatoolkit=11.8 -c conda-forge && conda install -y "pytorch<=1.12" pytorch-cuda=11.8 -c pytorch -c nvidia && pip install -e . && touch cryodrgn_3.1.0_installed
```
- good catch about 12.1. I have removed it for now.
- libcufft fixed as well, thanks!

**Comment by DavidHerreros** [comment]
Hi @azazellochg,

> Hi @DavidHerreros, thank you for a very quick response. The answers are below:
> 
> * cd into the folder is already done, not sure how you get an error:

True! Not sure then why I was getting that error... let me check again the installation probably something weird happened the first time I tried it :thinking: 

> 
> ```
> cd /public/EM/Scipion/scipion-dev/software/em
> mkdir /public/EM/Scipion/scipion-dev/software/em/cryodrgn-3.1.0
> cd /public/EM/Scipion/scipion-dev/software/em/cryodrgn-3.1.0
> cd .. && git clone -b v3.1.0-beta https://github.com/zhonge/cryodrgn.git cryodrgn-3.1.0 && cd cryodrgn-3.1.0; source /public/EM/Scipion/conda.rc&& conda create -y -n cryodrgn-3.1.0 python=3.10 && conda activate cryodrgn-3.1.0 && conda install -y cudatoolkit=11.8 -c conda-forge && conda install -y "pytorch<=1.12" pytorch-cuda=11.8 -c pytorch -c nvidia && pip install -e . && touch cryodrgn_3.1.0_installed
> ```
> 
> * good catch about 12.1. I have removed it for now.
> * libcufft fixed as well, thanks!

You're welcome!!

**Comment by delarosatrevin** [comment]
Hi @azazellochg, thanks for the update!

I will have a look in a couple of days.

**Review by DavidHerreros — APPROVED** [review]

**Comment by azazellochg** [comment]
@delarosatrevin I will run a few more tests on a different server this week-end and will merge on Monday

**Comment by azazellochg** [comment]
I've changed the installer again. Tested on Tesla T4, RTX 3090 and A100-40.

**Pull request merged**
