### PR TITLE
Cryodrgn2 support

### LINKED ISSUE #24: add abinitio protocol
https://github.com/zhonge/cryodrgn/blob/master/README.md#cryodrgn2----ab-initio-reconstruction

### PR DESCRIPTION
**Pull request by azazellochg**
Closes #24 and fixes chimera viewer

### CODE REVIEW

**Comment by azazellochg** [comment]
Analyze step still fails....

**Comment by azazellochg** [comment]
@fonsecareyna82 would you like to check if the changes are compatible with your web service?

**Comment by fonsecareyna82** [comment]
I have some installation problems with this branch

**Comment by azazellochg** [comment]
okay, let me try a clean install here

**Comment by azazellochg** [comment]
I've made some fixes, you could try again.

**Comment by fonsecareyna82** [comment]
Now, the installation was fine!!! I'll check the code today

**Review by fonsecareyna82 — APPROVED** [review]

**Pull request merged**
