### PR TITLE
Generating outputs

### PR DESCRIPTION
**Pull request by fonsecareyna82**

### CODE REVIEW

**Comment by azazellochg** [comment]
Thanks @fonsecareyna82 ! I'll try to review this closer to the end of the week if there's no urgency

**Comment by fonsecareyna82** [comment]
You're welcome @azazellochg !!! There's no hurry

**Comment by azazellochg** [comment]
@fonsecareyna82 I've made some changes, most importantly new ptcls set obj is removed. Please have a look.
Also, wha t is the purpose of utils.py?

**Comment by fonsecareyna82** [comment]
Yes, I saw that the ptcl class was removed. I solve with the extension(I don't know now why I implemented a new class). The utils.py purpose is to use by flexutils plugin later in order to plot a selected cluster in the flexutil viewer.

**Comment by fonsecareyna82** [comment]
I'll modify flexutils plugin

**Review by azazellochg — APPROVED** [review]

**Pull request merged**
